---
- hosts: all
  become: yes
  tasks:
  - name: Cheack and Print Linux Version
    debug: var=ansible_os_family

  - name: Debian
    apt: name=nginx state=latest
    when: ansible_os_family == "Debian"

  - name: RedHet
    yum: name=nginx state=latest
    when: ansible_os_family == "RedHet"
